

# 這裡的config是global, 所有連到這個config server的service都會讀到並套用這份設定
eureka:
  instance:
    hostname: configServer
  client:
    enabled: @eureka.client.enabled@
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://@eurekaServer.host@:@eurekaServer.port@/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: @configServer.git.url@
          
          
---
#-- for junit test---------
spring:
  profiles: development
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: file:///tmp/test/config-repo
