# 這裡的config只套用於app本身

####### development ######### 
spring:
  application:
    name: configServer
  profiles: development
  
  cloud:
    config:
      enabled: false
      
eureka:
  client:
    enabled: false



---
####### production #########
spring:
  application:
    name: configServer
  profiles: production

  cloud:
    config:
      enabled: true
      server:
        git:
          uri: @configServer.git.url@
          
eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://@eurekaServer.host@:@eurekaServer.port@/eureka/
      
          
          
          
          
---
#-- for junit test---------
spring:
  application:
    name: configServer
  profiles: junit
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: file:././target/repos/config-repo/

eureka:
  client:
    enabled: false

